package com.moo.eggu.ui.theme

import androidx.compose.ui.graphics.Color

val lightPrimary = Color(0xFF9A2BA2)
val lightOnPrimary = Color(0xFFFFFFFF)
val lightPrimaryContainer = Color(0xFFFFD6F9)
val lightOnPrimaryContainer = Color(0xFF37003C)
val lightSecondary = Color(0xFF6C586A)
val lightOnSecondary = Color(0xFFFFFFFF)
val lightSecondaryContainer = Color(0xFFF6DBF0)
val lightOnSecondaryContainer = Color(0xFF261625)
val lightTertiary = Color(0xFF825248)
val lightOnTertiary = Color(0xFFFFFFFF)
val lightTertiaryContainer = Color(0xFFFFDAD3)
val lightOnTertiaryContainer = Color(0xFF33110A)
val lightError = Color(0xFFBA1A1A)
val lightErrorContainer = Color(0xFFFFDAD6)
val lightOnError = Color(0xFFFFFFFF)
val lightOnErrorContainer = Color(0xFF410002)
val lightBackground = Color(0xFFFFFBFF)
val lightOnBackground = Color(0xFF1E1A1D)
val lightSurface = Color(0xFFFFFBFF)
val lightOnSurface = Color(0xFF1E1A1D)
val lightSurfaceVariant = Color(0xFFEDDEE8)
val lightOnSurfaceVariant = Color(0xFF4D444B)
val lightOutline = Color(0xFF7F747C)
val lightInverseOnSurface = Color(0xFFF8EEF2)
val lightInverseSurface = Color(0xFF342F32)
val lightInversePrimary = Color(0xFFFFA9FC)
val lightShadow = Color(0xFF000000)
val lightSurfaceTint = Color(0xFF9A2BA2)
val lightOutlineVariant = Color(0xFFD0C3CC)
val lightScrim = Color(0xFF000000)

val darkPrimary = Color(0xFFFFA9FC)
val darkOnPrimary = Color(0xFF590060)
val darkPrimaryContainer = Color(0xFF7E0287)
val darkOnPrimaryContainer = Color(0xFFFFD6F9)
val darkSecondary = Color(0xFFD9BFD4)
val darkOnSecondary = Color(0xFF3C2B3B)
val darkSecondaryContainer = Color(0xFF544152)
val darkOnSecondaryContainer = Color(0xFFF6DBF0)
val darkTertiary = Color(0xFFF6B8AA)
val darkOnTertiary = Color(0xFF4C261D)
val darkTertiaryContainer = Color(0xFF663B32)
val darkOnTertiaryContainer = Color(0xFFFFDAD3)
val darkError = Color(0xFFFFB4AB)
val darkErrorContainer = Color(0xFF93000A)
val darkOnError = Color(0xFF690005)
val darkOnErrorContainer = Color(0xFFFFDAD6)
val darkBackground = Color(0xFF1E1A1D)
val darkOnBackground = Color(0xFFE9E0E4)
val darkSurface = Color(0xFF1E1A1D)
val darkOnSurface = Color(0xFFE9E0E4)
val darkSurfaceVariant = Color(0xFF4D444B)
val darkOnSurfaceVariant = Color(0xFFD0C3CC)
val darkOutline = Color(0xFF998D96)
val darkInverseOnSurface = Color(0xFF1E1A1D)
val darkInverseSurface = Color(0xFFE9E0E4)
val darkInversePrimary = Color(0xFF9A2BA2)
val darkShadow = Color(0xFF000000)
val darkSurfaceTint = Color(0xFFFFA9FC)
val darkOutlineVariant = Color(0xFF4D444B)
val darkScrim = Color(0xFF000000)


val seed = Color(0xFFFD86FF)